# Generated by Django 4.2.7 on 2023-12-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='agent_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
