# Generated by Django 4.2.7 on 2023-12-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_customermessage_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
