# Generated by Django 4.2.7 on 2023-12-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_customermessage_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
